### ISSUE TITLE
Configuration Option to not raise errors when communicating with hipchat

### ISSUE THREAD

**Issue by RyanNaughton** [robertzk/hipchat#12]
Hipchat has been having increased downtime. This is a problem when using this package because a 500 returned from hipchat raises an exception in `hipchat::hipchat`. 

Unless the call to `hipchat::hipchat` is wrapped in a `tryCatch` every time, then this prevents the rest of the code from executing simply because we couldn't announce to hipchat.

Proposal: Add a configuration option to the package specifying whether it should default to `tryCatch` or to raising if an error occurs in the `hipchat::hipchat` function. Then, add an additional argument (exceptions_as_warnings) to the `hipchat::hipchat` function that overrides that global config and specifies whether to re-raise or catch any exceptions and turn them into warnings.

**Comment by robertzk** [comment]
Addressed by https://github.com/robertzk/hipchat/pull/14 thanks to @davluangu
